# AK & Sons Bespoke Joinery: every fact, project and photo the site uses.
# Sources: Instagram @ak_sonsbespokejoineryltd captions and location tags (assets/ig_manifest.json),
# Facebook recommendations (assets/reviews.json), Companies House (brief), scraped 2026-10-07.

SITE = 'https://aksonsbespokejoinery.co.uk'   # assumed; domain not chosen yet (gaps.md)

BIZ = {
    'name': 'AK & Sons Bespoke Joinery',
    'legal': 'AK & Sons Bespoke Joinery Ltd',
    'email': 'ak.sonsbespokejoinery@gmail.com',
    'town': 'Worksop',
    'county': 'Nottinghamshire',
    'postcode': 'S80 2EJ',
    'company_no': '15249959',
    'office': 'Unit 4 Rear Of 38 Church Walk, Worksop, Nottinghamshire, S80 2EJ',
    'facebook': 'https://www.facebook.com/AK.SONSbespokejoinery/',
    'fb_reviews': 'https://www.facebook.com/AK.SONSbespokejoinery/reviews',
    'instagram': 'https://www.instagram.com/ak_sonsbespokejoineryltd/',
}

# Category keys used by the /work/ filter
CATS = [
    ('built-in', 'Built-in furniture'),
    ('kitchens', 'Kitchens'),
    ('doors', 'Doors'),
    ('stairs', 'Staircases'),
    ('bars', 'Hallways and bars'),
    ('more', 'More joinery'),
]

# photos: list of (source id, alt text). First is the cover, 'second' is the hover frame.
# pair: (before, after) aligned 1:1 files for the slider. Text is the client's caption, corrected.
PROJECTS = [
    {
        'slug': 'harrogate-display-unit', 'title': 'Built-in display and storage unit', 'place': 'Harrogate', 'region': 'North Yorkshire',
        'cats': ['built-in'], 'ig': 'DdYOR0bjK0v',
        'work': ['CAD drawing', 'Made by our team', 'Fitted', 'LED shelf lighting'],
        'text': ['We have given this residential bathroom space a built-in display and storage unit, drawn in CAD, then manufactured and fitted by our team for the residents to enjoy.',
                 'LED strips run under every shelf, with painted shaker doors on the cupboards below.'],
        'cover': 'P00_04', 'second': 'P00_00',
        'photos': [('P00_01', 'Built-in display and storage unit with LED lighting under every shelf, Harrogate'),
                   ('P00_00', 'CAD drawing of the Harrogate display and storage unit, front elevation and plan'),
                   ('P00_04', 'The Harrogate unit seen from the side, painted shelves and shaker cupboard doors'),
                   ('P00_02', 'Close-up of the LED strips under the painted shelves'),
                   ('P00_03', 'Cupboard doors open below the lit shelves'),
                   ('P00_05', 'The finished unit across the full width of the wall')],
    },
    {
        'slug': 'tickhill-kitchen-pocket-doors', 'title': 'Wren kitchen, pocket doors and wall units', 'place': 'Tickhill', 'region': 'South Yorkshire',
        'cats': ['kitchens', 'doors'], 'ig': 'DcnWDBfjOM2',
        'work': ['Kitchen fitting', 'Pocket door system', 'Two full-height wall units'],
        'text': ['A Wren kitchen fit we completed in Tickhill. Our team fitted the pocket door system, supplied by Ironmongery Direct, with doors supplied by Howdens.',
                 'We then returned to fit the two full-height wall units after the quartz worktops and flooring works were carried out.'],
        'cover': 'P02_01', 'second': 'P02_00',
        'video': {'src': 'P02_00', 'alt': 'Walk-through of the finished Tickhill kitchen, starting at the black glazed pocket doors', 'title': 'Walk through the finished kitchen', 'text': 'From the black glazed pocket doors to the range cooker and the quartz worktops, as we left it.'},
        'photos': [('P02_01', 'Cream Wren kitchen with a black range cooker and dark wood floor, Tickhill'),
                   ('P02_02', 'Range cooker, black fridge freezer and the full-height wall units'),
                   ('P02_03', 'Quartz worktop run under the window'),
                   ('P02_00', 'Black glazed pocket doors between the kitchen and the hall')],
    },
    {
        'slug': 'worksop-hallway-understairs', 'title': 'Understairs storage and staircase refurb', 'place': 'Worksop', 'region': 'Nottinghamshire',
        'cats': ['stairs', 'built-in', 'bars'], 'ig': 'Dcjh4YHjKjm',
        'work': ['Understairs storage', 'Staircase refurb', 'Spindles, newel and handrail'],
        'text': ['We manufactured and fitted the storage under the stairs of this entrance hallway: panelled doors and a pull-out shoe rack, painted to suit the hall.',
                 'Then came the staircase refurb, with new spindles, newel posts and handrail.'],
        'cover': 'P04_00', 'second': 'P03_00',
        'pair': ('pair_before', 'pair_after', 'pair_during'),
        'photos': [('P04_00', 'Finished staircase with black metal spindles and green panelled understairs storage, Worksop'),
                   ('P03_00', 'The hallway before: open understairs and the old staircase'),
                   ('P03_01', 'During: understairs panelling fitted, pull-out shoe rack open'),
                   ('P03_02', 'After: new spindles, newel post and handrail over the panelled storage'),
                   ('P04_01', 'Looking up the refurbished staircase from the hall'),
                   ('P04_03', 'New oak handrail and spindles from the landing'),
                   ('P04_02', 'Spindles and handrail running up the stairs'),
                   ('P05_06', 'One of our team fitting the understairs doors')],
    },
    {
        'slug': 'carlton-in-lindrick-garage-bar', 'title': 'Garage turned into a home bar', 'place': 'Carlton in Lindrick', 'region': 'Nottinghamshire',
        'cats': ['bars'], 'ig': 'C9LP628ui2a',
        'work': ['Bar made in our workshop', 'Wall panelling', 'Flooring and stud walls', 'Part storage'],
        'text': ['A surprise 40th birthday present. Our team turned this garage into a home bar with part storage, working while the customer\'s husband was out at work and away for his birthday.',
                 'The bar was built in our workshop, then fitted on site with the panelling and skirting, ready for the decorator.'],
        'cover': 'P22_02', 'second': 'P20_01',
        'photos': [('P22_02', 'Blue panelled home bar with LED edge lighting in a converted garage, Carlton in Lindrick'),
                   ('P22_00', 'The bar counter, stools and neon sign'),
                   ('P20_05', 'Panelled corner with a bar table'),
                   ('P20_06', 'Bar counter and shelving from behind'),
                   ('P23_01', 'During: the bar and panelling in bare MDF before painting'),
                   ('P20_01', 'The garage before the work started')],
    },
    {
        'slug': 'worksop-glazed-double-doors', 'title': 'Black glazed double doors and internal doors', 'place': 'Worksop', 'region': 'Nottinghamshire',
        'cats': ['doors'], 'ig': 'DV1hrOIDHYE',
        'work': ['New partition and opening', 'Black glazed double doors', 'Internal doors and ironmongery'],
        'text': ['A new partition between the hall and the living room, framed with an opening for black glazed double doors.',
                 'We also hung new white panel doors with brass knobs through the hallway and landing.'],
        'cover': 'P15_04', 'second': 'P15_00',
        'photos': [('P15_04', 'Black glazed double doors in a new partition, Worksop'),
                   ('P15_03', 'The double doors closed, seen from the hall'),
                   ('P15_00', 'Before: the open room without the partition'),
                   ('P15_02', 'During: the new partition boarded with the door opening'),
                   ('P15_05', 'White panel door with a brass knob'),
                   ('P15_06', 'Brass door knob, close-up'),
                   ('P15_11', 'New internal doors on the landing')],
    },
    {
        'slug': 'banbury-media-walls', 'title': 'Media walls for a communal living room', 'place': 'Banbury', 'region': 'Oxfordshire',
        'cats': ['built-in'], 'ig': 'DZN4zT1jEhZ',
        'work': ['Built-in media walls', 'Electric fire surround', 'Open shelving'],
        'text': ['A built-in media wall for a communal living room, made for the patients to enjoy.',
                 'Open shelving either side, a recess for the electric fire and drawers along the base.'],
        'cover': 'P12_02', 'second': 'P12_04',
        'photos': [('P12_02', 'Walnut-finish built-in media wall with shelving and an electric fire, Banbury'),
                   ('P12_04', 'Grey oak-finish media wall with open shelving')],
    },
    {
        'slug': 'worksop-stair-refurbishment', 'title': 'Stair refurbishment', 'place': 'Worksop', 'region': 'Nottinghamshire',
        'cats': ['stairs'], 'ig': 'DaZ-nD5jBF3',
        'work': ['New treads and risers', 'Stairs strengthened', 'Handrail'],
        'text': ['A stair refurbishment completed by our team, with materials supplied by the customer.',
                 'The treads and risers were strengthened, so no more squeaky stairs.'],
        'cover': 'P07_01', 'second': 'P07_00',
        'photos': [('P07_01', 'Refurbished stairs with oak treads and black risers, Worksop'),
                   ('P07_02', 'The full flight with the new handrail'),
                   ('P07_00', 'Before: worn and painted treads')],
    },
    {
        'slug': 'mansfield-external-door', 'title': 'External door and frame', 'place': 'Mansfield', 'region': 'Nottinghamshire',
        'cats': ['doors'], 'ig': 'C8-TxrWsa2p',
        'work': ['Door and frame made by our team', 'Arched fanlight frame', 'Fitted on site'],
        'text': ['An external door and frame set, made by our team on the bench and fitted in place of the old door.'],
        'cover': 'P28_07', 'second': 'P28_03',
        'photos': [('P28_07', 'New grey external double door with an arched fanlight, Mansfield'),
                   ('P28_03', 'The arched frame glued and clamped on the bench'),
                   ('P28_02', 'Door frame parts laid out before assembly'),
                   ('P28_04', 'Door leaf boarded and ready for the glazing panel'),
                   ('P28_06', 'The finished door from inside'),
                   ('P28_00', 'Before: the old door and frame')],
    },
    {
        'slug': 'harthill-wren-kitchen', 'title': 'Wren kitchen fit for a local builder', 'place': 'Harthill', 'region': 'Rotherham',
        'cats': ['kitchens'], 'ig': 'DdRoelgDGTi',
        'work': ['Kitchen fitting', 'Larder units', 'Ready for worktops and flooring'],
        'text': ['A Wren kitchen fit we completed for a local construction company.',
                 'Units and larders in, so the quartz worktop team have something to work to, with the flooring following.'],
        'cover': 'P01_13', 'second': 'P01_07',
        'photos': [('P01_13', 'Cream Wren kitchen under a roof lantern, Harthill'),
                   ('P01_03', 'Wall units and extractor fitted'),
                   ('P01_07', 'One of our team setting the larder unit'),
                   ('P01_12', 'Tall units and the oven housing'),
                   ('P01_11', 'Looking through the kitchen to the island'),
                   ('P01_08', 'Corner run under the lantern')],
    },
    {
        'slug': 'east-markham-glazed-oak-doors', 'title': 'Glazed oak double doors', 'place': 'East Markham', 'region': 'Nottinghamshire',
        'cats': ['doors'], 'ig': 'DA8wGr1oXAX',
        'work': ['New opening', 'Solid oak threshold', 'Double door casing', 'Glazed oak doors and architraves'],
        'text': ['Marking out, cutting and removing the plasterboard, then a new solid oak threshold and internal double door casing.',
                 'We fitted two glazed oak doors with their ironmongery and finished with architraves, ready for the decorator.'],
        'cover': 'P17_03', 'second': 'P17_00',
        'photos': [('P17_03', 'Glazed oak double doors fitted between two rooms, East Markham'),
                   ('P17_01', 'The new opening seen from the next room'),
                   ('P17_00', 'Marking out the opening in the plasterboard'),
                   ('P17_02', 'Solid oak threshold in the new opening')],
    },
    {
        'slug': 'worksop-glass-balustrade', 'title': 'Staircase refurb with glass balustrade', 'place': 'Worksop', 'region': 'Nottinghamshire',
        'cats': ['stairs'], 'ig': 'C8-qxJ1NT2b',
        'work': ['Staircase refurb', 'Glass balustrade', 'Newels and handrail'],
        'text': ['A staircase refurb completed by the team: glass panels between painted newels, with a new handrail to the landing.'],
        'cover': 'P25_03', 'second': 'P25_00',
        'photos': [('P25_03', 'Glass balustrade and grey painted newels on the landing, Worksop'),
                   ('P25_00', 'Glass panels running down the stairs'),
                   ('P25_02', 'Landing balustrade from the top step'),
                   ('P25_01', 'Handrail and glass detail')],
    },
    {
        'slug': 'worksop-hallway-alcove', 'title': 'Hallway alcove unit', 'place': 'Worksop', 'region': 'Nottinghamshire',
        'cats': ['built-in', 'bars'], 'ig': 'DZzHEb2jD2g',
        'work': ['Alcove shelving', 'Cupboard below', 'Panelling'],
        'text': ['Some unwanted space not being used to its potential: an alcove unit we manufactured and fitted in this entrance hallway, with shelves above and a cupboard below.'],
        'cover': 'P11_01', 'second': 'P11_00',
        'photos': [('P11_01', 'Painted alcove unit with open shelves and a cupboard, Worksop hallway'),
                   ('P11_00', 'Before: the unused corner of the hallway')],
    },
    {
        'slug': 'leicester-bar-tops', 'title': 'Replacement bar tops', 'place': 'Leicester', 'region': 'Leicestershire',
        'cats': ['bars'], 'ig': 'DZ2TAxGjMfo',
        'work': ['Bar tops made to specification', 'Fitted on site'],
        'text': ['Replacement bar tops we manufactured and fitted to specification at a residential retirement village.'],
        'cover': 'P10_00', 'second': 'P10_02',
        'photos': [('P10_00', 'New wooden bar top in a retirement village lounge, Leicester'),
                   ('P10_01', 'The bar top end and the counter below'),
                   ('P10_02', 'Sink cut into the new bar top')],
    },
    {
        'slug': 'crowborough-media-wall', 'title': 'Built-in media wall', 'place': 'Crowborough', 'region': 'East Sussex',
        'cats': ['built-in'], 'ig': 'DbpjdL6jDnc',
        'work': ['Built-in media wall', 'Open shelving', 'Cupboards'],
        'text': ['A built-in media wall for a residential living room, with open shelving either side of the screen and cupboards along the base.'],
        'cover': 'P06_01', 'second': 'P06_00',
        'photos': [('P06_01', 'Built-in media wall with open shelving, Crowborough'),
                   ('P06_00', 'The media wall seen straight on')],
    },
    {
        'slug': 'harworth-pergola', 'title': 'Garden pergola', 'place': 'Harworth', 'region': 'Nottinghamshire',
        'cats': ['more'], 'ig': 'C8-TBStstAv',
        'work': ['Timber pergola', 'Slatted screens', 'Roof panels'],
        'text': ['A garden pergola completed by our team, with slatted screens and a clear roof over the patio.'],
        'cover': 'P29_01', 'second': 'P29_02',
        'photos': [('P29_01', 'Grey painted timber pergola over a patio, Harworth'),
                   ('P29_02', 'Clear roof panels and the slatted screen'),
                   ('P29_00', 'The pergola from the garden'),
                   ('P29_03', 'Slatted side screen')],
    },
    {
        'slug': 'kilton-garage-conversion', 'title': 'Garage conversion', 'place': 'Kilton', 'region': 'Nottinghamshire',
        'cats': ['more'], 'ig': 'C8-qScjN_H3',
        'work': ['Stud walls', 'Window opening', 'New room'],
        'text': ['A garage conversion completed by the team: stud walls, a new window where the garage door was, and a finished room.'],
        'cover': 'P26_07', 'second': 'P26_00',
        'photos': [('P26_07', 'Finished playroom in the converted garage, Kilton'),
                   ('P26_09', 'The house with a window where the garage door was'),
                   ('P26_00', 'Before: the garage door'),
                   ('P26_01', 'During: stud walls inside the garage'),
                   ('P26_06', 'New hallway into the converted room')],
    },
    {
        'slug': 'sheffield-cut-roof', 'title': 'Traditional cut roof for a local builder', 'place': 'Sheffield', 'region': 'South Yorkshire',
        'cats': ['more'], 'ig': 'C8-rhpztlSS',
        'work': ['Traditional cut roof', 'Dormer framing'],
        'text': ['A traditional cut roof completed by our team for a local builder.'],
        'cover': 'P24_03', 'second': 'P24_01',
        'photos': [('P24_03', 'Traditional cut roof with dormer framing, Sheffield'),
                   ('P24_01', 'Rafters and steel ridge beam'),
                   ('P24_06', 'Dormer framing from inside the roof'),
                   ('P24_00', 'One of the team on the roof deck')],
    },
]

HOME_CARDS = ['tickhill-kitchen-pocket-doors', 'carlton-in-lindrick-garage-bar', 'banbury-media-walls',
              'worksop-glazed-double-doors', 'worksop-stair-refurbishment', 'mansfield-external-door']

SERVICES = [
    {'name': 'Built-in furniture', 'data': 'Display and storage units, media walls, alcoves, LED shelving', 'cat': 'built-in', 'photos': ['P00_01', 'P12_02', 'P11_01']},
    {'name': 'Kitchen fitting', 'data': 'Wren, Howdens and others, fitted and finished', 'cat': 'kitchens', 'photos': ['P02_01', 'P01_13', 'P02_02']},
    {'name': 'Internal doors', 'data': 'Glazed double doors, pocket door systems, oak and panel doors', 'cat': 'doors', 'photos': ['P15_04', 'P17_03', 'P02_00']},
    {'name': 'Staircases', 'data': 'Refurbs, treads and risers, spindles, glass balustrades', 'cat': 'stairs', 'photos': ['P04_00', 'P07_01', 'P25_03']},
    {'name': 'Hallways, panelling and bars', 'data': 'Understairs storage, panelling, home bars, bar tops', 'cat': 'bars', 'photos': ['P22_02', 'P03_02', 'P10_00']},
    {'name': 'CAD drawings', 'data': 'A measured drawing of the piece before anything is made', 'cat': 'built-in', 'photos': ['P00_00', 'P00_04', 'P28_03']},
]

FACTS = [
    {'text': 'Over 35 years’ experience combined between us', 'source': 'Facebook intro and Instagram bio, 2026-10'},
    {'text': '100% recommended on Facebook from 8 reviews', 'source': 'facebook.com/AK.SONSbespokejoinery/reviews, 8 of 8 recommended, 2026-10-07'},
    {'text': 'Based in Worksop, Nottinghamshire, S80 2EJ', 'source': 'Facebook About and Companies House'},
    {'text': 'The bar was built in their workshop', 'source': 'customer post (Instagram reel C9QDFMrKGX5), Carlton in Lindrick'},
]
